<a href="https://colab.research.google.com/github/Morfinic/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics**

In [ ]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

---
**1D Array**

---

In [6]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [7]:
print(x)

[1 2 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(3,)

In [11]:
x.size

3

In [13]:
x.dtype

dtype('int64')

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

---
**2D Array**

---

In [18]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [22]:
print(x)

[[ 1  2]
 [-3  1]]


In [21]:
x.ndim

2

In [20]:
x.shape

(2, 2)

In [24]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [25]:
x.shape

(2, 3)

---
**3D Array**

---

In [31]:
x = np.array([
    [[4, 3, 1],
     [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]
])
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]

 [[3 2 1]
  [4 3 2]]]


In [32]:
x.ndim

3

In [33]:
x.shape

(3, 2, 3)

# **Typy danych**

In [34]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [35]:
A = np.array([1.0, 2.0, 3.0])
A.dtype

dtype('float64')

In [36]:
A = np.array([1, 2, 3], dtype="float")
A.dtype

dtype('float64')

In [37]:
A

array([1., 2., 3.])

In [38]:
A = np.array([1, 2, 3], dtype="complex")
A.dtype

dtype('complex128')

In [39]:
A = np.array([1.0, 2.0, 3.7], dtype="int")
A.dtype

dtype('int64')

In [41]:
A

array([1, 2, 3])

In [42]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [44]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [46]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# **Tworzenie tablic**

In [47]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.zeros(shape=(3, 5), dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.ones(shape=(5, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
np.full(shape=(4, 4), fill_value=4, dtype="int")

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(start=4, stop=8)

array([4, 5, 6, 7])

In [57]:
np.arange(start=10, stop=151, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [58]:
np.arange(start=100, stop=0, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [59]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [60]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [61]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
A.reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [66]:
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# **Podstawowe operacje na tablicach**

In [72]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

print("A:", A, " B:", B)

A: [3 1 4 2]  B: [ 3 -1  3  2]


In [73]:
A + B

array([6, 0, 7, 4])

In [74]:
A - B

array([0, 2, 1, 0])

In [75]:
A * B

array([ 9, -1, 12,  4])

In [76]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [81]:
abs(B)

array([3, 1, 3, 2])

In [82]:
np.add(A, B)

array([6, 0, 7, 4])

In [84]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [86]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [87]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [78]:
A + 3

array([6, 4, 7, 5])

In [79]:
A * 2

array([6, 2, 8, 4])

In [80]:
A + 3 * B

array([12, -2, 13,  8])

In [92]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6,0], [-1, 2]])
print(X, "\n\n", Y)

[[ 1  3]
 [-2  0]] 

 [[ 6  0]
 [-1  2]]


In [93]:
X * Y

array([[6, 0],
       [2, 0]])

In [94]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [96]:
np.dot(Y, X)

array([[ 6, 18],
       [-5, -3]])

In [95]:
X @ Y

array([[  3,   6],
       [-12,   0]])

# **Generowanie liczb pseudolosowych**

In [97]:
np.random.seed(0)

In [98]:
np.random.randn()

1.764052345967664

In [99]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [100]:
np.random.randn(2, 5)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982]])

In [102]:
np.random.rand()

0.7742336894342167

In [103]:
np.random.rand(5)

array([0.45615033, 0.56843395, 0.0187898 , 0.6176355 , 0.61209572])

In [104]:
np.random.rand(5, 3)

array([[0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835],
       [0.36371077, 0.57019677, 0.43860151]])

In [108]:
np.random.randint(5)

3

In [110]:
np.random.randint(low=0, high=100, size=5, dtype=np.int8)

array([76, 75, 27, 50, 39], dtype=int8)

In [114]:
np.random.choice(np.random.randint(low=5, high=20, size=8))

5

In [119]:
np.random.choice(["sql", "python", "java"])

'python'

In [121]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.random.shuffle(data)
data

array([6, 3, 8, 7, 5, 4, 2, 9, 1, 0])

# **Podstawowe funkcje**

In [125]:
np.exp(1)

2.718281828459045

In [126]:
np.sqrt(4)

2.0

In [128]:
np.all([2, 0, 1])

False

In [130]:
np.any(np.array([0, 0, 9]))

True

In [131]:
bool(1.3)

True

In [134]:
A = np.random.rand(5)
A

array([0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [135]:
np.argmax(A)

4

In [136]:
A[np.argmax(A)]

0.896038387509077

In [137]:
np.argmin(A)

0

In [138]:
A[np.argmin(A)]

0.28847643704852866

In [139]:
np.argsort(A)

array([0, 3, 1, 2, 4])

In [140]:
np.max(A)

0.896038387509077

In [141]:
np.min(A)

0.28847643704852866

In [142]:
np.mean(A)

0.5540015711656106

In [144]:
np.median(A)

0.43328806198204406

In [145]:
np.std(A)

0.23144954668752118

# **Indeksowanie, wycinanie**

In [146]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [147]:
A[2]

2

In [148]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [150]:
A[2:5 + 1]

array([2, 3, 4, 5])

In [151]:
A[:2]

array([0, 1])

In [153]:
A[[2, 4]]

array([2, 4])

In [154]:
A[-1]

19

In [156]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [158]:
A[1:3, 2:5]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [166]:
A[2, 2]

12

# **Iteracja po tablicach**

In [162]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [165]:
for row in A:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [168]:
for row in A:
    print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [169]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


# **Zmian rozmiaru tablic**

In [170]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [171]:
A.shape

(4, 5)

In [172]:
A.reshape(10, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [173]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [174]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# **Maski logiczne**

In [178]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [179]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [188]:
np.bitwise_and(A > -5, A < 5)

True

In [199]:
np.bitwise_or(A < -5, A > 5)

False