<a href="https://colab.research.google.com/github/Morfinic/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Norma wektora, długość wektora w $R^2$**

In [2]:
import numpy as np

In [7]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [8]:
np.linalg.norm(v1)

4.123105625617661

# **Norma euklidesowa w $R^n$**

In [9]:
v2 = np.array([-10, 10, 13])
v2

array([-10,  10,  13])

In [10]:
np.linalg.norm(v2)

19.209372712298546

# **Odległość dwóch punktów w przestrzeni $R^n$**

In [11]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

# **Mnożenie macierzy**

In [12]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, end="\n")
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [13]:
Z = X @ Y
Z

array([[ 2],
       [-6]])

# **Wyznacznik macierzy**

In [14]:
A = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
print(A)

[[1 2 3]
 [0 4 5]
 [0 0 6]]


In [16]:
round(np.linalg.det(A))

24

# **Ślad macierzy**

In [18]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

# **Macierz jednostkowa**

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# **Macierz odwrotna**

In [22]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [23]:
np.set_printoptions(precision=4, suppress=True)
B @ A

array([[ 1., -0.],
       [ 0.,  1.]])

In [24]:
A @ B

array([[1., 0.],
       [0., 1.]])

# **Macierz transponowana**

In [25]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [26]:
A.T

array([[ 2, -1],
       [ 4,  3]])

# **Rozwiązywanie układów równań**

2x + 4y = 10 \\
x - y = -1

In [27]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [28]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [30]:
X = np.linalg.inv(A) @ B
print(X)

[[1.]
 [2.]]


In [31]:
X.shape

(2, 1)